version: '2.2'
services:
  api:
    container_name: test
    image: webapitest
    ports:
      - 8080:8080
    depends_on:
      - 'mongo'
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27100:27017